soldier:
  health: 100
  health_when_reviving: 50
  grenade_distance_short_reach: 20
  grenade_distance_long_reach: 40
  grenade_time_change_to_long_reach: 2000
  grenade_time_explode_in_hand: 6000
  matrix_range_to_revive: 1
  times_can_be_revived: 3

soldierStates:
  time_being_attacked: 0.1
  time_calling_air_strike: 2.5
  time_permanent_dead: 10
  time_moving: 0.1
  time_reloading: 0.5
  time_shooting: 0.1
  time_throwing_explosive_g: 1
  time_throwing_smoke_g: 1

weapons:
  idf:
    mag_capacity: 1000
    burst_capacity: 20
    close_range_damage: 30
    long_range_damage: 10
    matrix_range_to_reduce_damage: 5
    rate_of_fire: 0.1

  p90:
    mag_capacity: 300
    burst_capacity: 10
    damage: 15
    rate_of_fire: 0.1

  scout:
    mag_capacity: 20
    damage: 60
    damage_reduction_per_hit: 10
    rate_of_fire: 1

explosiveGrenade:
  damage: 50
  time_to_reThrow_grenade: 1
  radius_range: 8

smokeGrenade:
  time_to_reThrow_grenade: 30
  radius_range: 8

grenadeStates:
  time_exploding: 0.4
  time_thrown_grenade: 1

generalToAllZombies:
  sight_distance_after_being_hit: 100

infected:
  health: 100
  damage: 10
  distance_to_hit: 1
  sight_distance: 30
  probability_walk: [0, 40]
  probability_run: [40, 100]
  probability_jump: [0, 0]


jumper:
  health: 100
  damage: 10
  damage_by_jump: 30
  distance_to_hit: 1
  distance_to_hit_by_jump: 1
  sight_distance: 30
  probability_walk: [ 0, 10 ]
  probability_run: [ 10, 50 ]
  probability_jump: [ 50, 100 ]

witch:
  health: 200
  damage: 30
  probability_scream: 1
  zombies_created_for_screaming: 2
  distance_to_hit: 1
  sight_distance: 30
  probability_walk: [ 0, 40 ]
  probability_run: [ 40, 100 ]
  probability_jump: [ 0, 0 ]

spear:
  health: 100
  damage: 10
  distance_to_hit: 2
  sight_distance: 30
  probability_walk: [ 0, 40 ]
  probability_run: [ 40, 100 ]
  probability_jump: [ 0, 0 ]

venom:
  health: 100
  damage_close_range: 30
  damage_long_range: 10
  distance_to_hit_close_range: 2
  distance_to_hit_long_range: 10
  sight_distance: 30
  probability_walk: [ 0, 40 ]
  probability_run: [ 40, 100 ]
  probability_jump: [ 0, 0 ]

zombieStates:
  time_attacking: 0.6
  time_jumping: 0
  time_running: 0.01
  time_screaming: 1.2
  time_stunned: 10
  time_walking: 0.2
  time_being_attacked: 0.3

mapLogic:
  matrix_movements_per_cell: 2

clearTheZone:
  time_respawn_zombies: 8
  total_quantity_zombies: 50
  zombies_probability_respawn:
    infected: [ 0, 30 ]
    witch: [ 30, 50 ]
    jumper: [ 50, 60 ]
    spear: [ 60, 80 ]
    venom: [ 80, 100 ]

survival:
  time_respawn_zombies: 8
  time_zombies_getting_stronger: 15
  health_power_up: 10
  damage_power_up: 5
  zombies_probability_respawn:
    infected: [ 0, 30 ]
    witch: [ 30, 50 ]
    jumper: [ 50, 60 ]
    spear: [ 60, 80 ]
    venom: [ 80, 100 ]

gameFactory:
  zombies_probability_respawn:
    infected: [ 0, 30 ]
    witch: [ 40, 50 ]
    jumper: [ 50, 60 ]
    spear: [ 60, 80 ]
    venom: [ 80, 100 ]

airStrike:
  radius_range_safe_space: 10
  damage: 30
  time_reCall_air_strike: 1

airStrikeStates:
  time_exploding: 0.4
  time_incoming: 3