soldier:
  health: 100
  grenade_distance_reach: 4

soldierStates:
  time_being_attacked: 0.1
  time_calling_air_strike: 0.3
  time_moving: 0.1
  time_reloading: 0.5
  time_shooting: 0.1
  time_throwing_explosive_g: 0.2
  time_throwing_smoke_g: 0.2

weapons:
  idf:
    mag_capacity: 50
    close_range_damage: 30
    long_range_damage: 15

  p90:
    mag_capacity: 30
    damage: 15

  scout:
    mag_capacity: 20
    damage: 40
    damage_reduction_per_hit: 10

explosiveGrenade:
  damage: 40
  time_to_reThrow_grenade: 30
  radius_range: 3

smokeGrenade:
  time_to_reThrow_grenade: 30
  radius_range: 3

grenadeStates:
  time_exploding: 0.08
  time_thrown_grenade: 1

infected:
  health: 100
  damage: 10

jumper:
  health: 100
  damage: 10

witch:
  health: 200
  damage: 30
  probability_scream: 1
  zombies_created_for_screaming: 2

spear:
  health: 100
  damage: 10

zombieStates:
  time_attacking: 0.2
  time_jumping: 0.2
  time_running: 0.01
  time_screaming: 0.9
  time_stunned: 10
  time_walking: 0.2
  time_being_attacked: 0.3

mapLogic:
  matrix_movements_per_cell: 2

clearTheZone:
  time_respawn_zombies: 5
  total_quantity_zombies: 80
  zombies_probability_respawn:
    infected: [0, 40]
    witch: [40, 70]
    jumper: [70, 100]
    spear: [0, 0]
    venom: [0, 0]

survival:
  time_respawn_zombies: 5
  time_zombies_getting_stronger: 10
  health_power_up: 10
  zombies_probability_respawn:
    infected: [0, 40]
    witch: [40, 70]
    jumper: [70, 100]
    spear: [0, 0]
    venom: [0, 0]

gameFactory:
  zombies_probability_respawn:
    infected: [0, 40]
    witch: [40, 50]
    jumper: [50, 100]
    spear: [0, 0]
    venom: [0, 0]

airStrike:
  radius_range_safe_space: 2
  damage: 30
  time_reCall_air_strike: 120

airStrikeStates:
  time_exploding: 0.08
  time_incoming: 1