@startuml

participant Client1
participant Client2
participant PlayerSender1
participant PlayerSender2
participant MatchMananger
participant Game

Client1 -> PlayerSender1: create(scenario_name, game_mode, game_players)

PlayerSender1 -> MatchMananger: create(scenario_name, game_mode, game_players,)

MatchMananger -> Game: new()

MatchMananger -> Game: start()

MatchMananger -> PlayerSender1: <ok>

PlayerSender1 -> Client1: create(scenario_code)

Client2 -> PlayerSender2: join(scenario_code)

PlayerSender2 -> MatchMananger: join(scenario_code)

MatchMananger -> Game: add_player()

MatchMananger -> PlayerSender2: <ok>

PlayerSender2 -> Client2: join(ok)

@enduml
