@startuml

participant Client1
participant ClientSender1
participant ClientReceiver1

participant Servidor

loop hasta que cierre el juego

Client1 -> Client1: serialize(key_event)

Client1 -> Client1: try_push(std::vector<char>)

ClientSender1 -> ClientSender1: pop()

ClientSender1 -> Servidor: send: std::vector<char>

Servidor -> Servidor: update game

Servidor -> ClientReceiver1: send: GameDTO

ClientReceiver1 -> ClientReceiver1: push (GameDTO)

Client1 -> Client1: try_pop(GameDTO)
end

@enduml
