@startuml

participant Client1
participant ClientSender1
participant ClientReceiver1

participant Servidor

Client1 -> Client1: try_push(move: LEFT)

ClientSender1 -> ClientSender1: pop()

ClientSender1 -> Servidor: move: LEFT

Servidor -> Servidor: move(LEFT)

Servidor -> ClientReceiver1: GameDTO

ClientReceiver1 -> ClientReceiver1: push (GameDTO)

Client1 -> Client1: try_pop(GameDTO)

Client1 -> Client1: try_push(move: UP)

Client1 -> Client1: try_push(shoot)

ClientSender1 -> ClientSender1: pop()

ClientSender1 -> Servidor: move: UP

ClientSender1 -> ClientSender1: pop()

ClientSender1 -> Servidor: shoot

Servidor -> Servidor: move(LEFT)

Servidor -> Servidor: shoot

Servidor -> ClientReceiver1: GameDTO

ClientReceiver1 -> ClientReceiver1: push (GameDTO)

Client1 -> Client1: try_pop(GameDTO)

@enduml
