@startuml

participant Lobby1
participant LobbySender1
participant LobbyReceiver1

participant Lobby2
participant LobbySender2
participant LobbyReceiver2

participant Servidor

activate Lobby1
Lobby1 -> Servidor: connect()

Servidor -> Lobby1: player_id

Lobby1 -> Lobby1: push(create(...))

LobbySender1 -> LobbySender1: pop()

LobbySender1 -> Servidor: create(scenario_name, game_mode, game_players)

Servidor -> Servidor: exist(scenario_name)

Servidor -> LobbyReceiver1: create(scenario_code)

LobbySender2 -> Servidor: join(scenario_code)

Servidor -> Servidor: exist(scenario_code)

Servidor -> Servidor: can_join(scenario_code)

Servidor -> LobbyReceiver2: join(confirm_code)

LobbySender1 -> Servidor: start()

LobbySender2 -> Servidor: start()

Servidor -> Servidor: start_game()

@enduml
